### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by Rohit3523** [el/canvas-table#3]
TypeError: (row[cellIndex] || "").split is not a function or its return value is not iterable
    at CanvasTable.calculateColumnTextWidths (/home/ubuntu/wa/node_modules/canvas-table/dist/index.js:115:60)
    at CanvasTable.calculateColumnWidths (/home/ubuntu/wa/node_modules/canvas-table/dist/index.js:130:39)
    at /home/ubuntu/wa/node_modules/canvas-table/dist/index.js:56:26
    at new Promise (<anonymous>)
    at CanvasTable.<anonymous> (/home/ubuntu/wa/node_modules/canvas-table/dist/index.js:48:20)
    at Generator.next (<anonymous>)
    at /home/ubuntu/wa/node_modules/canvas-table/dist/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ubuntu/wa/node_modules/canvas-table/dist/index.js:4:12)

**Comment by el** [comment]
You need to provide data for each cell. I am going to change this to make it optional in the next release.
