### ISSUE TITLE
Tring to use split where it does not exist

### ISSUE THREAD

**Issue by Tsopic** [el/canvas-table#8]
From lib folder index is giving an error

https://github.com/el/canvas-table/blob/master/lib/index.ts

`let [cellValue] = row[cellIndex].split("\n");`

```
(node:2293) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at CanvasTable.generateRows (/Users/user_name/project/node_modules/canvas-table/lib/index.ts:315:50)
    at /Users/user_name/project/node_modules/canvas-table/lib/index.ts:79:22
    at new Promise (<anonymous>)
    at CanvasTable.<anonymous> (/Users/user_name/project/node_modules/canvas-table/lib/index.ts:65:16)
    at Generator.next (<anonymous>)
    at /Users/user_name/project/node_modules/canvas-table/dist/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/user_name/project/node_modules/canvas-table/dist/index.js:4:12)
    at CanvasTable.generateTable (/Users/user_name/project/node_modules/canvas-table/dist/index.js:47:16)
```

**Comment by el** [comment]
I am guessing you have passed an undefined (or did not pass the cell). Anyways, I will fix the error and handle this case.
